name: PHP Demo
on: [push]
jobs:
  build:

    runs-on: "ubuntu-20.04"

    steps:
    - uses: actions/checkout@v2

    - name: Docker Compose Action
      uses: isbang/compose-action@v1.0.0

#    - name: Validate composer.json and composer.lock
#      run: composer validate --strict

#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v2
#      with:
#        path: vendor
#        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-php-

#    - name: Install dependencies
#      run: composer install --prefer-dist --no-progress

#    - name: Run test suite
#      run: composer run-script tests
